import type { Metadata } from "next";
import "./globals.css";

import { roboto } from "@/lib/fonts";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "Dr Techno",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${roboto.variable} antialiased`}
      >
        {children}
      <Footer />
      </body>
    </html>
  );
}
