import type { Metadata } from "next";
import "@/app/globals.css";

import { roboto } from "@/lib/fonts";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import ReduxProvider from '@/app/ReduxProvider';
import AuthInitializer from "@/app/AuthInitializer";

export const metadata: Metadata = {
  title: "Dr Techno",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${roboto.variable} antialiased`}
      >
        <ReduxProvider>
          <AuthInitializer />
          <Header />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}